version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "4356:4356"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
